[y, Fs] = audioread('sa_re_ga_ma.wav');
y = y(:, 1:1);
y_gaussian = smoothdata(y, 'gaussian');
y_movmean = smoothdata(y, 'movmean');
y_movmedian = smoothdata(y, 'movmedian');
y_loess = smoothdata(y, 'loess');
y_lowess = smoothdata(y, 'lowess');
y_rlowess = smoothdata(y, 'rlowess');
y_rloess = smoothdata(y, 'rloess');
y_sgolay = smoothdata(y, 'sgolay');
sound(y, Fs);
sound(y_gaussian, Fs);
sound(y_movmean, Fs);
sound(y_movmedian, Fs);
sound(y_loess, Fs);%%%%% This gives the best result.
sound(y_lowess, Fs);
sound(y_rloess, Fs);
sound(y_rlowess, Fs);
sound(y_sgolay, Fs);
subplot(9, 1, 1);
plot(y);
title('Original Sound');
subplot(9, 1, 2);
plot(y_gaussian);
title('gaussian');
subplot(9, 1, 3, 'r');
plot(y_movmean);
title('movmean');
subplot(9, 1, 4);
plot(y_movmedian);
title('movmedian')
subplot(9, 1, 5);
plot(y_loess);
title('loess');
subplot(9, 1, 6);
plot(y_lowess);
title('lowess');
subplot(9, 1, 7);
plot(y_rloess);
title('rloess');
subplot(9, 1, 8);
plot(y_rlowess);
title('rlowess');
subplot(9, 1, 9);
plot(y_sgolay);
title('sgolay');